### ISSUE TITLE
read_dns_queries.py

### ISSUE THREAD

**Issue by Samarium-Z** [akamai/Information-based-Heavy-Hitters-for-Real-Time-DNS-Exfiltration-Detection#3]
Hi there~
Running the main_tune.py seems to require 'read_dns_queries.py'. Could u please provide it?
Thanks!

**Comment by yozery1** [comment]
Thanks for raising my attention, this is now resolved by #4

**Comment by Samarium-Z** [comment]
Sincerely thanks!!
